### ISSUE TITLE
Request to add resource_link_id to launchInfo

### ISSUE THREAD

**Issue by ciatph** [harvard-edtech/caccl-lti#3]
Hi, thank you so much for your CACCL project. This has helped us a lot in managing Canvas LTI apps.

I would like to request if it’s possible to add Canvas’ `resource_link_id` to the parsed `req.session.launchInfo` in [parseLaunch.js](https://github.com/harvard-edtech/caccl-lti/blob/master/parseLaunch.js).

It would be great to have it also included along with the other `launchInfo` parameters. We are planning to use this as a unique ID to differentiate LTI launches from several Modules within a course.

TIA!

**Comment by gabeabrams** [comment]
Great idea! I'll get right on that.

**Comment by ciatph** [comment]
Thank you so much, the update for `resourceLinkId` looks great!
